name: CI/CD Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Repo’yu klonla
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2) GitHub Pages’a deploy et
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages       # sayfanın yayınlanacağı branch
          folder: ./             # deploy edilecek klasör (kök)

      # Sonuç: npm kurulumu veya build aşaması yok
